add_newline = true

[character]
success_symbol = "[\\$](bold fg:#99b7dc)"
error_symbol = "[\\$](bold red)"

[directory]
read_only = "\uf023"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[$path [$read_only](bg:#99b7dc fg:red)](fg:#fffafa bg:#99b7dc)[](fg:#99b7dc) "

