set -g default-shell '/bin/zsh'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"
# set -g @plugin 'sainnhe/tmux-fzf'

# UI
set-option -g status-position bottom

# true color
set -g default-terminal "screen-256color"
set -sg terminal-overrides ",*:RGB"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set -as terminal-features ',*:clipboard'

# mouse
set -g mouse on

# key bindings
set-option -g prefix C-Space  # prefix key を Control-Space に
unbind-key C-b            # unbind-key を Control-b に
bind-key C-Space send-prefix
bind | split-window -h  # prefix-| で垂直分割 
bind _ split-window -v  # prefix-_ で

# solve "ESC IN TMUX OR GNU SCREEN IS DELAYED"
set -sg escape-time 10

run '~/.tmux/plugins/tpm/tpm'

