set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'sainnhe/tmux-fzf'

set-option -g prefix C-w
unbind-key C-b
bind-key C-o send-prefix

bind | split-window -h
bind _ split-window -v

run '~/.tmux/plugins/tpm/tpm'

