# Formatter configuration for `nix fmt` and the `formatting` flake check.
#
# Previously `just fmt` shelled out to whatever `treefmt` happened to be on
# PATH, which was the nixfmt-tree wrapper and therefore only ever formatted
# .nix files -- the lua, toml and yaml in this repo were never touched.
{
  projectRootFile = "flake.nix";

  programs = {
    nixfmt.enable = true;
    stylua.enable = true; # home-manager/neovim/config
    taplo.enable = true; # config.toml
    yamlfmt = {
      enable = true; # .github/workflows
      # Without this yamlfmt collapses the blank lines between workflow steps,
      # which is most of what makes them readable.
      settings.formatter.retain_line_breaks_single = true;
    };
  };

  settings.global.excludes = [
    # Generated by bin2nix; regenerating is the only supported way to change it.
    "packages/*.nix"
    # Chezmoi executes this as a Go template; it is not literal TOML.
    "chezmoi/dot_codex/modify_config.toml"
    "flake.lock"
    "*.md"
    "LICENSE"
  ];
}
