# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "biome";
  version = "2.4.14";

  src = fetchurl {
    url = "https://github.com/biomejs/biome/releases/download/%40biomejs/biome%402.4.14/biome-darwin-arm64";
    hash = "sha256-E4lRcNJrCpgYUyuE8z4EopgLRsu36G1D7MYGxr0bHmM=";
  };

  dontUnpack = true;

  installPhase = ''
    mkdir -p $out/bin
    cp $src $out/bin/biome
    chmod +x $out/bin/biome
  '';
}
