# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "codex";
  version = "0.128.0";

  src = fetchurl {
    url = "https://github.com/openai/codex/releases/download/rust-v0.128.0/codex-aarch64-apple-darwin.tar.gz";
    hash = "sha256-8GggLoqJjCQMjAaEAbzNMLp7VvYfX/zRSD1UXUeq89U=";
  };

  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp codex-* $out/bin/codex || cp codex $out/bin/codex
    chmod +x $out/bin/codex
  '';
}
