approval_policy = "on-request"
approvals_reviewer = "auto_review"
model = "gpt-5.6-sol"
model_provider = "openai"
model_reasoning_effort = "medium"
service_tier = "fast"
web_search = "live"
plan_mode_reasoning_effort = "medium"

[features]
hooks = true
plugins = true

[plugins."claude-code-setup@home-manager"]
enabled = true

[plugins."claude-md-management@home-manager"]
enabled = true

[plugins."claude-mem@home-manager"]
enabled = true

[plugins."code-review@home-manager"]
enabled = true

[plugins."code-simplifier@home-manager"]
enabled = true

[plugins."commit-commands@home-manager"]
enabled = true

[plugins."context7@home-manager"]
enabled = true

[plugins."feature-dev@home-manager"]
enabled = true

[plugins."frontend-design@home-manager"]
enabled = true

[plugins."gopls-lsp@home-manager"]
enabled = true

[plugins."ralph-loop@home-manager"]
enabled = true

[plugins."rust-analyzer-lsp@home-manager"]
enabled = true

[plugins."security-guidance@home-manager"]
enabled = true

[plugins."skill-creator@home-manager"]
enabled = true

[plugins."superpowers@home-manager"]
enabled = true

[projects."/Users/earlgray/dev/dotfiles"]
trust_level = "trusted"

[hooks.state]

[hooks.state."/Users/earlgray/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:cdb45465c937a59b479d2e100e37d477d6c5884cc718fd2c4d65b4a6570f3d7a"

[hooks.state."claude-mem@home-manager:plugin/hooks/codex-hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:86febee762af4f8108e7881061dcfb56c83e0dce5895fb0de92401357b847d6f"

[hooks.state."claude-mem@home-manager:plugin/hooks/codex-hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:3a42cc9271ee65328dde3a9afe2199416194644c8467687107d621e0b84dd0ce"

[hooks.state."claude-mem@home-manager:plugin/hooks/codex-hooks.json:session_start:0:0"]
trusted_hash = "sha256:e87c134f96569d4c873334f90aa4e05ca7cd97c33d7f1039f21e834ea55d88f4"

[hooks.state."claude-mem@home-manager:plugin/hooks/codex-hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:ec28069a1699801e83b6c227f730f4cd89616e8ef24e5b1ffdbc68066f89b735"

[hooks.state."claude-mem@home-manager:plugin/hooks/codex-hooks.json:stop:0:0"]
trusted_hash = "sha256:bc8fcabc7e0a38d90e26757207c40907b8b6e967256e6eb74f8f49f9cc4bf1"
