vim.loader.enable()

require("options")
require("autocmds")
require("keymaps")

require("plugins.colorscheme")
-- Before anything that resolves icons, so mini.icons is the one it finds.
require("plugins.mini")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.blink-cmp")
require("plugins.conform")
require("plugins.nvim-lint")
require("plugins.gitsigns")
require("plugins.fzf-lua")
require("plugins.which-key")
require("plugins.oil")
require("plugins.toggleterm")
require("plugins.editor")
