# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "actionlint";
  version = "1.7.12";

  src = fetchurl {
    url = "https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_darwin_arm64.tar.gz";
    hash = "sha256-q6nO0t7o0n/syj3H/rGn+aUsrvoetG8ycepmtuDmlT8=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'actionlint' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'actionlint' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/actionlint
  '';

  meta.mainProgram = "actionlint";
}
