# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "aqua";
  version = "2.60.0";

  src = fetchurl {
    url = "https://github.com/aquaproj/aqua/releases/download/v2.60.0/aqua_linux_amd64.tar.gz";
    hash = "sha256-dhZ4gGI1UVdnHpg9aKp/TEsmkfu3ZSgFEvJFpkUj4+o=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'aqua' -type f -exec cp {} $out/bin/aqua \;
    chmod +x $out/bin/aqua
  '';

}