# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "aqua";
  version = "2.60.1";

  src = fetchurl {
    url = "https://github.com/aquaproj/aqua/releases/download/v2.60.1/aqua_darwin_arm64.tar.gz";
    hash = "sha256-GaWrKKEjjEu+BsQLy84254tSg4uwVdDVfNSoRNFlvcQ=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'aqua' -type f -exec cp {} $out/bin/aqua \;
    chmod +x $out/bin/aqua
  '';


  meta.mainProgram = "aqua";
}