# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "bat";
  version = "0.26.1";

  src = fetchurl {
    url = "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-aarch64-apple-darwin.tar.gz";
    hash = "sha256-4wvv8md5yb9gu1QeHXkEYlDLdDePJ1f46yUK/dsZ4RQ=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'bat' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'bat' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/bat
  '';

  meta.mainProgram = "bat";
}
