# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "bat";
  version = "0.26.1";

  src = fetchurl {
    url = "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-aarch64-apple-darwin.tar.gz";
    hash = "sha256-4wvv8md5yb9gu1QeHXkEYlDLdDePJ1f46yUK/dsZ4RQ=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp bat-* $out/bin/bat || cp bat $out/bin/bat
    chmod +x $out/bin/bat
  '';

}