# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "biome";
  version = "2.5.10";

  src = fetchurl {
    url = "https://github.com/biomejs/biome/releases/download/%40biomejs/biome%402.5.10/biome-darwin-arm64";
    hash = "sha256-govCloB2W2VrajVN4B2af59REeavmbBM7+BtCcbS29o=";
  };

  dontUnpack = true;

  installPhase = ''
    install -Dm755 $src $out/bin/biome
  '';

  meta.mainProgram = "biome";
}
