# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "biome";
  version = "2.5.9";

  src = fetchurl {
    url = "https://github.com/biomejs/biome/releases/download/%40biomejs/biome%402.5.9/biome-darwin-arm64";
    hash = "sha256-fYtR3shX/6iqNc5eqjpEds1ivtATrcKJa/Q8rApnp5s=";
  };


  dontUnpack = true;

  installPhase = ''
    mkdir -p $out/bin
    cp $src $out/bin/biome
    chmod +x $out/bin/biome
  '';


  meta.mainProgram = "biome";
}