# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "buf";
  version = "1.70.0";

  src = fetchurl {
    url = "https://github.com/bufbuild/buf/releases/download/v1.70.0/buf-Darwin-arm64.tar.gz";
    hash = "sha256-nOwjZY3wk9UPMxhYDhfx4wnUW4F5J/IuneMPePPU1Fs=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'buf' -type f -exec cp {} $out/bin/buf \;
    chmod +x $out/bin/buf
  '';

}