# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "buf";
  version = "1.70.0";

  src = fetchurl {
    url = "https://github.com/bufbuild/buf/releases/download/v1.70.0/buf-Linux-x86_64.tar.gz";
    hash = "sha256-GEmL2tvc6AeSzgjCxZ4MSfFXqj9dmw+cbj23lb4gi50=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'buf' -type f -exec cp {} $out/bin/buf \;
    chmod +x $out/bin/buf
  '';

}