# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "buf";
  version = "1.72.0";

  src = fetchurl {
    url = "https://github.com/bufbuild/buf/releases/download/v1.72.0/buf-Darwin-arm64.tar.gz";
    hash = "sha256-vgQK4Mo4EQPf2mijZzhpXE2z5I3o6RQSrNw9mR85uR4=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'buf' -type f -exec cp {} $out/bin/buf \;
    chmod +x $out/bin/buf
  '';


  meta.mainProgram = "buf";
}