# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "codex";
  version = "0.144.1";

  src = fetchurl {
    url = "https://github.com/openai/codex/releases/download/rust-v0.144.1/codex-aarch64-apple-darwin.tar.gz";
    hash = "sha256-iOcqyL0wgV99GOYtrDM9wgzjrRy6lL4WSaGXfdm/27g=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'codex' -type f -exec cp {} $out/bin/codex \;
    chmod +x $out/bin/codex
  '';


  meta.mainProgram = "codex";
}