# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ pkgs }:
{

  biome = pkgs.callPackage ./biome.nix { };

  codex = pkgs.callPackage ./codex.nix { };

}