# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ pkgs }:
{

  actionlint = pkgs.callPackage ./actionlint.nix { };

  aqua = pkgs.callPackage ./aqua.nix { };

  buf = pkgs.callPackage ./buf.nix { };

  fzf = pkgs.callPackage ./fzf.nix { };

  golangci-lint = pkgs.callPackage ./golangci-lint.nix { };

  just = pkgs.callPackage ./just.nix { };

  lazygit = pkgs.callPackage ./lazygit.nix { };

  protolint = pkgs.callPackage ./protolint.nix { };

  ripgrep = pkgs.callPackage ./ripgrep.nix { };

  taplo = pkgs.callPackage ./taplo.nix { };

  xh = pkgs.callPackage ./xh.nix { };

}