# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "delta";
  version = "0.19.2";

  src = fetchurl {
    url = "https://github.com/dandavison/delta/releases/download/0.19.2/delta-0.19.2-aarch64-apple-darwin.tar.gz";
    hash = "sha256-m+NmEqWhPp44bcSY+45Q3IfHLuQrY9sOoFsy+Zpyppo=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'delta' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'delta' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/delta
  '';

  meta.mainProgram = "delta";
}
