# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "delta";
  version = "0.19.2";

  src = fetchurl {
    url = "https://github.com/dandavison/delta/releases/download/0.19.2/delta-0.19.2-aarch64-apple-darwin.tar.gz";
    hash = "sha256-m+NmEqWhPp44bcSY+45Q3IfHLuQrY9sOoFsy+Zpyppo=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'delta' -type f -exec cp {} $out/bin/delta \;
    chmod +x $out/bin/delta
  '';

}