# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl, unzip }:


stdenv.mkDerivation {
  pname = "dprint";
  version = "0.55.2";

  src = fetchurl {
    url = "https://github.com/dprint/dprint/releases/download/0.55.2/dprint-aarch64-apple-darwin.zip";
    hash = "sha256-6bqO15iPM1BQGoz4r5LaYWzeyNnVyDHAaSk8WHMRtJ0=";
  };


  nativeBuildInputs = [ unzip ];
  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'dprint' -type f -exec cp {} $out/bin/dprint \;
    chmod +x $out/bin/dprint
  '';


  meta.mainProgram = "dprint";
}