# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl, unzip }:

stdenv.mkDerivation {
  pname = "dprint";
  version = "0.54.0";

  src = fetchurl {
    url = "https://github.com/dprint/dprint/releases/download/0.54.0/dprint-aarch64-apple-darwin.zip";
    hash = "sha256-HWqPsU1my6DwSXOO3Uqzsa/B3m2TbNMuSD4zKEz9Gt4=";
  };


  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'dprint' -type f -exec cp {} $out/bin/dprint \;
    chmod +x $out/bin/dprint
  '';

}