# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{
  stdenv,
  fetchurl,
  unzip,
}:

stdenv.mkDerivation {
  pname = "dprint";
  version = "0.55.2";

  src = fetchurl {
    url = "https://github.com/dprint/dprint/releases/download/0.55.2/dprint-aarch64-apple-darwin.zip";
    hash = "sha256-6bqO15iPM1BQGoz4r5LaYWzeyNnVyDHAaSk8WHMRtJ0=";
  };

  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'dprint' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'dprint' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/dprint
  '';

  meta.mainProgram = "dprint";
}
