# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "fd";
  version = "10.4.2";

  src = fetchurl {
    url = "https://github.com/sharkdp/fd/releases/download/v10.4.2/fd-v10.4.2-aarch64-apple-darwin.tar.gz";
    hash = "sha256-Yj3Ar8gbkuTUYGs4DXvJGRa6e5eBQmPlVNUJI6OeSAo=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'fd' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'fd' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/fd
  '';

  meta.mainProgram = "fd";
}
