# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "fd";
  version = "10.4.2";

  src = fetchurl {
    url = "https://github.com/sharkdp/fd/releases/download/v10.4.2/fd-v10.4.2-aarch64-apple-darwin.tar.gz";
    hash = "sha256-Yj3Ar8gbkuTUYGs4DXvJGRa6e5eBQmPlVNUJI6OeSAo=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'fd' -type f -exec cp {} $out/bin/fd \;
    chmod +x $out/bin/fd
  '';


  meta.mainProgram = "fd";
}