# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "fzf";
  version = "0.73.1";

  src = fetchurl {
    url = "https://github.com/junegunn/fzf/releases/download/v0.73.1/fzf-0.73.1-darwin_arm64.tar.gz";
    hash = "sha256-0n/WjAT7m0L3xzo/fTgGmnTTCOQBdPZKByx0chPpcoY=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'fzf' -type f -exec cp {} $out/bin/fzf \;
    chmod +x $out/bin/fzf
  '';

}