# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "fzf";
  version = "0.74.2";

  src = fetchurl {
    url = "https://github.com/junegunn/fzf/releases/download/v0.74.2/fzf-0.74.2-darwin_arm64.tar.gz";
    hash = "sha256-1g3bNjVlZqxpuufDUE6IiRbPdHya0hMhQcCSKbHije4=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'fzf' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'fzf' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/fzf
  '';

  meta.mainProgram = "fzf";
}
