# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "fzf";
  version = "0.73.1";

  src = fetchurl {
    url = "https://github.com/junegunn/fzf/releases/download/v0.73.1/fzf-0.73.1-linux_amd64.tar.gz";
    hash = "sha256-8yUsLDZrwXANPIV4HsjJaVmYknrBJ4cOsEnO6i1UD4o=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'fzf' -type f -exec cp {} $out/bin/fzf \;
    chmod +x $out/bin/fzf
  '';

}