# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{
  stdenv,
  fetchurl,
  unzip,
}:

stdenv.mkDerivation {
  pname = "gh";
  version = "2.98.0";

  src = fetchurl {
    url = "https://github.com/cli/cli/releases/download/v2.98.0/gh_2.98.0_macOS_arm64.zip";
    hash = "sha256-jPsCfMUxBnXyuDDqyPmGXBFVpF/8+XV/aZ/dWiIEbKQ=";
  };

  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'gh' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'gh' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/gh
  '';

  meta.mainProgram = "gh";
}
