# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl, unzip }:


stdenv.mkDerivation {
  pname = "gh";
  version = "2.97.0";

  src = fetchurl {
    url = "https://github.com/cli/cli/releases/download/v2.97.0/gh_2.97.0_macOS_arm64.zip";
    hash = "sha256-pYuP13tBejj0egtU0TcMWbD82zJMzJygArCZj3xMmZ4=";
  };


  nativeBuildInputs = [ unzip ];
  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'gh' -type f -exec cp {} $out/bin/gh \;
    chmod +x $out/bin/gh
  '';


  meta.mainProgram = "gh";
}