# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "gitleaks";
  version = "8.30.1";

  src = fetchurl {
    url = "https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_darwin_arm64.tar.gz";
    hash = "sha256-tAqwrlXFBZY+Nl8nGo04Ru+8FwqhfyYH8T32EKmutqU=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'gitleaks' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'gitleaks' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/gitleaks
  '';

  meta.mainProgram = "gitleaks";
}
