# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "golangci-lint";
  version = "2.12.2";

  src = fetchurl {
    url = "https://github.com/golangci/golangci-lint/releases/download/v2.12.2/golangci-lint-2.12.2-darwin-arm64.tar.gz";
    hash = "sha256-qcVEmHMbMSj3ngkL5hEPPl//zMYXsIFC7SRNQSbHPyk=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'golangci-lint' -type f -exec cp {} $out/bin/golangci-lint \;
    chmod +x $out/bin/golangci-lint
  '';


  meta.mainProgram = "golangci-lint";
}