# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "hyperfine";
  version = "1.20.0";

  src = fetchurl {
    url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-jucGcBZiBEfJ0tYjTsmkaA+Vi3rZg1SbVjNGaPYwdbU=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp hyperfine-* $out/bin/hyperfine 2>/dev/null || cp hyperfine $out/bin/hyperfine
    chmod +x $out/bin/hyperfine
  '';

}