# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "hyperfine";
  version = "1.20.0";

  src = fetchurl {
    url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-jucGcBZiBEfJ0tYjTsmkaA+Vi3rZg1SbVjNGaPYwdbU=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'hyperfine' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'hyperfine' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/hyperfine
  '';

  meta.mainProgram = "hyperfine";
}
