# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "hyperfine";
  version = "1.20.0";

  src = fetchurl {
    url = "https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine-v1.20.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-jucGcBZiBEfJ0tYjTsmkaA+Vi3rZg1SbVjNGaPYwdbU=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'hyperfine' -type f -exec cp {} $out/bin/hyperfine \;
    chmod +x $out/bin/hyperfine
  '';


  meta.mainProgram = "hyperfine";
}