# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "just";
  version = "1.56.0";

  src = fetchurl {
    url = "https://github.com/casey/just/releases/download/1.56.0/just-1.56.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-81eY1LzcTbAg7vfShTrZi7+5ek0p7mlboELxjn/tzBE=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'just' -type f -exec cp {} $out/bin/just \;
    chmod +x $out/bin/just
  '';


  meta.mainProgram = "just";
}