# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "just";
  version = "1.58.0";

  src = fetchurl {
    url = "https://github.com/casey/just/releases/download/1.58.0/just-1.58.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-UK4+mWyXSgvzLqfRD0lQcN8z8bQ+Bhaydp49SCHtj0g=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'just' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'just' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/just
  '';

  meta.mainProgram = "just";
}
