# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "just";
  version = "1.54.0";

  src = fetchurl {
    url = "https://github.com/casey/just/releases/download/1.54.0/just-1.54.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-p3b8UBVJH4RYCHW8ba095Z+k9HownMrEnRKHy1X5tZk=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'just' -type f -exec cp {} $out/bin/just \;
    chmod +x $out/bin/just
  '';


  meta.mainProgram = "just";
}