# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "lazygit";
  version = "0.64.0";

  src = fetchurl {
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.64.0/lazygit_0.64.0_darwin_arm64.tar.gz";
    hash = "sha256-340t0nzcEHV4Xxq7hbdP45P83B8/32yytYf+s85yujM=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'lazygit' -type f -exec cp {} $out/bin/lazygit \;
    chmod +x $out/bin/lazygit
  '';


  meta.mainProgram = "lazygit";
}