# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "lazygit";
  version = "0.62.2";

  src = fetchurl {
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.62.2/lazygit_0.62.2_darwin_arm64.tar.gz";
    hash = "sha256-8xHZa2ZrSGV2Djnzln7f178wtdCeUqG8euUR9r390Cw=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp lazygit-* $out/bin/lazygit 2>/dev/null || cp lazygit $out/bin/lazygit
    chmod +x $out/bin/lazygit
  '';

}