# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "lazygit";
  version = "0.62.2";

  src = fetchurl {
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.62.2/lazygit_0.62.2_linux_x86_64.tar.gz";
    hash = "sha256-i5pMLQlpy+qStFyVbdKkThunaQDJ30nxxgmEBFzneYQ=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'lazygit' -type f -exec cp {} $out/bin/lazygit \;
    chmod +x $out/bin/lazygit
  '';

}