# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "mise";
  version = "2026.6.6";

  src = fetchurl {
    url = "https://github.com/jdx/mise/releases/download/v2026.6.6/mise-v2026.6.6-macos-arm64.tar.gz";
    hash = "sha256-vO/hGQ+xfJN79Q5T6py+VFSnTEj1uliZrVH5OOkfzMQ=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'mise' -type f -exec cp {} $out/bin/mise \;
    chmod +x $out/bin/mise
  '';

}