# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{
  stdenv,
  fetchurl,
  unzip,
}:

stdenv.mkDerivation {
  pname = "opencode";
  version = "1.18.25";

  src = fetchurl {
    url = "https://github.com/anomalyco/opencode/releases/download/v1.18.25/opencode-darwin-arm64.zip";
    hash = "sha256-YGsJci2YBpYF4WA3+4w8fI67/tm6cTB5pe+y5bBlric=";
  };

  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'opencode' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'opencode' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/opencode
  '';

  meta.mainProgram = "opencode";
}
