# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "oxc";
  version = "1.69.0";

  src = fetchurl {
    url = "https://github.com/oxc-project/oxc/releases/download/apps_v1.69.0/oxlint-aarch64-apple-darwin.tar.gz";
    hash = "sha256-SHfyXrKedCTMbGlRA7Ii0N/uzNfyiowlfusH4RQ76Ow=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp oxc-* $out/bin/oxc 2>/dev/null || cp oxc $out/bin/oxc
    chmod +x $out/bin/oxc
  '';

}