# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "oxc";
  version = "1.73.0";

  src = fetchurl {
    url = "https://github.com/oxc-project/oxc/releases/download/apps_v1.73.0/oxlint-aarch64-apple-darwin.tar.gz";
    hash = "sha256-8nspWWha4TaUqDp9QgFUtEDWtPYv0pQsE2Zm4qs8wsw=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'oxc' -type f -exec cp {} $out/bin/oxc \;
    chmod +x $out/bin/oxc
  '';


  meta.mainProgram = "oxc";
}