# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "protolint";
  version = "0.56.4";

  src = fetchurl {
    url = "https://github.com/yoheimuta/protolint/releases/download/v0.56.4/protolint_0.56.4_linux_amd64.tar.gz";
    hash = "sha256-lNCpEPTaau9jszG7nLLcvG7D5DdKEhPwKRn4iP55Ykk=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'protolint' -type f -exec cp {} $out/bin/protolint \;
    chmod +x $out/bin/protolint
  '';

}