# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "protolint";
  version = "0.56.4";

  src = fetchurl {
    url = "https://github.com/yoheimuta/protolint/releases/download/v0.56.4/protolint_0.56.4_darwin_arm64.tar.gz";
    hash = "sha256-MlPwjSrvtY+GEXM2vwZne3tzdHZTpEb+U57MUuNLU3E=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'protolint' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'protolint' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/protolint
  '';

  meta.mainProgram = "protolint";
}
