# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "ripgrep";
  version = "15.2.0";

  src = fetchurl {
    url = "https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-N1Cy6T834MaSZX2ldNcBmhAcAITaBaeQyD/TNbrZc+Q=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'rg' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'rg' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/rg
  '';

  meta.mainProgram = "rg";
}
