# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "ripgrep";
  version = "15.1.0";

  src = fetchurl {
    url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-aarch64-apple-darwin.tar.gz";
    hash = "sha256-N46XMokXbKDGBUBU7n9jGgZYdKNSv0Pw+mDvB5trpxU=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'rg' -type f -exec cp {} $out/bin/rg \;
    chmod +x $out/bin/rg
  '';

}