# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "starship";
  version = "1.26.0";

  src = fetchurl {
    url = "https://github.com/starship/starship/releases/download/v1.26.0/starship-aarch64-apple-darwin.tar.gz";
    hash = "sha256-xAsnsR9YBBHgaPL6bBvngwo4fAvEepTR038ysFTFNh0=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'starship' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'starship' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/starship
  '';

  meta.mainProgram = "starship";
}
