# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "starship";
  version = "1.25.1";

  src = fetchurl {
    url = "https://github.com/starship/starship/releases/download/v1.25.1/starship-aarch64-apple-darwin.tar.gz";
    hash = "sha256-EGKiNjSJuTNVKbgyBEcvAmM8CPw2CfGzJb5eujb+tjE=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'starship' -type f -exec cp {} $out/bin/starship \;
    chmod +x $out/bin/starship
  '';

}