# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "StyLua";
  version = "2.5.2";

  src = fetchurl {
    url = "https://github.com/JohnnyMorganz/StyLua/releases/download/v2.5.2/stylua-macos-aarch64.zip";
    hash = "sha256-kv8IieFjJIAbwHJpKXS7Z/gWHmIBD8kPlsYqF/gfMsc=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp StyLua-* $out/bin/StyLua || cp StyLua $out/bin/StyLua
    chmod +x $out/bin/StyLua
  '';

}