# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{
  stdenv,
  fetchurl,
  unzip,
}:

stdenv.mkDerivation {
  pname = "StyLua";
  version = "2.5.2";

  src = fetchurl {
    url = "https://github.com/JohnnyMorganz/StyLua/releases/download/v2.5.2/stylua-macos-aarch64.zip";
    hash = "sha256-kv8IieFjJIAbwHJpKXS7Z/gWHmIBD8kPlsYqF/gfMsc=";
  };

  nativeBuildInputs = [ unzip ];

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'stylua' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'stylua' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/stylua
  '';

  meta.mainProgram = "stylua";
}
