# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl, unzip }:


stdenv.mkDerivation {
  pname = "StyLua";
  version = "2.5.2";

  src = fetchurl {
    url = "https://github.com/JohnnyMorganz/StyLua/releases/download/v2.5.2/stylua-macos-aarch64.zip";
    hash = "sha256-kv8IieFjJIAbwHJpKXS7Z/gWHmIBD8kPlsYqF/gfMsc=";
  };


  nativeBuildInputs = [ unzip ];
  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'stylua' -type f -exec cp {} $out/bin/stylua \;
    chmod +x $out/bin/stylua
  '';


  meta.mainProgram = "stylua";
}