# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "taplo";
  version = "0.10.0";

  src = fetchurl {
    url = "https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-darwin-aarch64.gz";
    hash = "sha256-cTc0MUw+cYlLnndRPFNJg17vvVKQhEWg1zsMfcRpNH0=";
  };


  dontUnpack = true;

  installPhase = ''
    mkdir -p $out/bin
    gunzip -c $src > $out/bin/taplo
    chmod +x $out/bin/taplo
  '';

}