# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "taplo";
  version = "0.10.0";

  src = fetchurl {
    url = "https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-linux-x86_64.gz";
    hash = "sha256-j+GWuJTM+QcvmNThAToYAwbhfSRIMLA5hu5ejqvrYVY=";
  };


  dontUnpack = true;

  installPhase = ''
    mkdir -p $out/bin
    gunzip -c $src > $out/bin/taplo
    chmod +x $out/bin/taplo
  '';

}