# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{
  stdenv,
  fetchurl,
  gzip,
}:

stdenv.mkDerivation {
  pname = "taplo";
  version = "0.10.0";

  src = fetchurl {
    url = "https://github.com/tamasfe/taplo/releases/download/0.10.0/taplo-darwin-aarch64.gz";
    hash = "sha256-cTc0MUw+cYlLnndRPFNJg17vvVKQhEWg1zsMfcRpNH0=";
  };

  dontUnpack = true;

  nativeBuildInputs = [ gzip ];

  installPhase = ''
    mkdir -p $out/bin
    gzip -dc $src > $out/bin/taplo
    chmod +x $out/bin/taplo
  '';

  meta.mainProgram = "taplo";
}
