# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "television";
  version = "0.15.8";

  src = fetchurl {
    url = "https://github.com/alexpasmantier/television/releases/download/0.15.8/tv-0.15.8-aarch64-apple-darwin.tar.gz";
    hash = "sha256-5aKNjVzcMlKbflN5TZ73rLV43irAn1QE/r+aMTmkga4=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp television-* $out/bin/television 2>/dev/null || cp television $out/bin/television
    chmod +x $out/bin/television
  '';

}