# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "television";
  version = "0.15.9";

  src = fetchurl {
    url = "https://github.com/alexpasmantier/television/releases/download/0.15.9/tv-0.15.9-aarch64-apple-darwin.tar.gz";
    hash = "sha256-lK5xd9SZ9051RCQ//pyCNxGDyhGmNj8Ziks9Din4JzI=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'tv' -type f -exec cp {} $out/bin/tv \;
    chmod +x $out/bin/tv
  '';

}