# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl, unzip }:


stdenv.mkDerivation {
  pname = "tree-sitter";
  version = "0.26.10";

  src = fetchurl {
    url = "https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.10/tree-sitter-cli-macos-arm64.zip";
    hash = "sha256-R6HulPOWEdKMebqmGj9721/RsHZCjxj9gIJijcLsoto=";
  };


  nativeBuildInputs = [ unzip ];
  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'tree-sitter' -type f -exec cp {} $out/bin/tree-sitter \;
    chmod +x $out/bin/tree-sitter
  '';


  meta.mainProgram = "tree-sitter";
}