# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by github-release-updater
# Run 'just update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "tree-sitter";
  version = "0.26.9";

  src = fetchurl {
    url = "https://github.com/tree-sitter/tree-sitter/releases/download/v0.26.9/tree-sitter-cli-macos-arm64.zip";
    hash = "sha256-hugaeO7pb0/XMOQ1iezIAmP340vnoFWMzr/5pJLorZc=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp tree-sitter-* $out/bin/tree-sitter || cp tree-sitter $out/bin/tree-sitter
    chmod +x $out/bin/tree-sitter
  '';

}