# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "uv";
  version = "0.11.23";

  src = fetchurl {
    url = "https://github.com/astral-sh/uv/releases/download/0.11.23/uv-aarch64-apple-darwin.tar.gz";
    hash = "sha256-ce+d6F24IHSbOxK3WFYk7ieenFr8vG+CNrw9YoxDBbA=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'uv' -type f -exec cp {} $out/bin/uv \;
    chmod +x $out/bin/uv
  '';


  meta.mainProgram = "uv";
}