# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "uv";
  version = "0.11.21";

  src = fetchurl {
    url = "https://github.com/astral-sh/uv/releases/download/0.11.21/uv-aarch64-apple-darwin.tar.gz";
    hash = "sha256-H5IdSRul/+6ndOsE1mgezuN5EBNBy7FQA5SZO1Qb8/Q=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp uv-* $out/bin/uv 2>/dev/null || cp uv $out/bin/uv
    chmod +x $out/bin/uv
  '';

}