# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "vale";
  version = "3.15.1";

  src = fetchurl {
    url = "https://github.com/vale-cli/vale/releases/download/v3.15.1/vale_3.15.1_macOS_arm64.tar.gz";
    hash = "sha256-loxti/IFK8l6okJ0I0zEZtvMJJtVrOM904LCzfqTsIw=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'vale' -type f -exec cp {} $out/bin/vale \;
    chmod +x $out/bin/vale
  '';

}