# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "vale";
  version = "3.18.0";

  src = fetchurl {
    url = "https://github.com/vale-cli/vale/releases/download/v3.18.0/vale_3.18.0_macOS_arm64.tar.gz";
    hash = "sha256-TX3pvag3naFM1FBIUAGZxUlBMYdSbQkTODrYIoZq1D0=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'vale' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'vale' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/vale
  '';

  meta.mainProgram = "vale";
}
