# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "vale";
  version = "3.17.1";

  src = fetchurl {
    url = "https://github.com/vale-cli/vale/releases/download/v3.17.1/vale_3.17.1_macOS_arm64.tar.gz";
    hash = "sha256-gMrPhe8j9Tz913NV7EGm75muwTbxXfs1F3I0gvNVk/k=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'vale' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'vale' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/vale
  '';

  meta.mainProgram = "vale";
}
