# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "worktrunk";
  version = "0.74.0";

  src = fetchurl {
    url = "https://github.com/max-sixty/worktrunk/releases/download/v0.74.0/worktrunk-aarch64-apple-darwin.tar.xz";
    hash = "sha256-1awDuPPfDRRKLAUidLcKb3UKjB6CsbK6NIJXdJ/aWuM=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'wt' -type f -exec cp {} $out/bin/wt \;
    chmod +x $out/bin/wt
  '';


  meta.mainProgram = "wt";
}