# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file

{ stdenv, fetchurl }:

stdenv.mkDerivation {
  pname = "worktrunk";
  version = "0.73.0";

  src = fetchurl {
    url = "https://github.com/max-sixty/worktrunk/releases/download/v0.73.0/worktrunk-aarch64-apple-darwin.tar.xz";
    hash = "sha256-TQ2TUYz4o/tvtBOFEYM6qwjjI55+xTn+MkckdQs2DZQ=";
  };

  sourceRoot = ".";

  installPhase = ''
    bin=$(find . -type f -perm -u+x -name 'wt' | sort | head -n 1)
    if [ -z "$bin" ]; then
      echo "bin2nix: no executable named 'wt' found in archive" >&2
      exit 1
    fi
    install -Dm755 "$bin" $out/bin/wt
  '';

  meta.mainProgram = "wt";
}
