# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "xh";
  version = "0.26.1";

  src = fetchurl {
    url = "https://github.com/ducaale/xh/releases/download/v0.26.1/xh-v0.26.1-aarch64-apple-darwin.tar.gz";
    hash = "sha256-xm4vZs8NSGBm+LxrteC1Z/piUZs8ufaLSiz++LzpKJI=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    find . -name 'xh' -type f -exec cp {} $out/bin/xh \;
    chmod +x $out/bin/xh
  '';


  meta.mainProgram = "xh";
}