# THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
# Generated by bin2nix
# Run 'bin2nix update' to regenerate this file


{ stdenv, fetchurl }:


stdenv.mkDerivation {
  pname = "xh";
  version = "0.25.3";

  src = fetchurl {
    url = "https://github.com/ducaale/xh/releases/download/v0.25.3/xh-v0.25.3-aarch64-apple-darwin.tar.gz";
    hash = "sha256-OIavHfdEpE9vjaN9UeP3M8FLNa6z9Ggo7lKJcK1wiVE=";
  };


  sourceRoot = ".";

  installPhase = ''
    mkdir -p $out/bin
    tar xzf $src
    cp xh-* $out/bin/xh 2>/dev/null || cp xh $out/bin/xh
    chmod +x $out/bin/xh
  '';

}